"""Add shopkeeper info and reward points

Revision ID: e9dfa64789e2
Revises: 
Create Date: 2026-09-06 08:36:29.537712
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'e9dfa64789e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('shopkeeper_name', sa.String(length=255), nullable=True))
    op.add_column('complaints', sa.Column('shop_address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('reward_points', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reward_points')
    op.drop_column('complaints', 'shop_address')
    op.drop_column('complaints', 'shopkeeper_name')
    # ### end Alembic commands ###
